services:
  postgres:
    container_name: PostgreSQL
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=mydb
    # volumes:
      # - my-db:/var/lib/mysql
# Names our volume
# volumes:
  # my-db: